# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d977ce1c7ffc4a340839efc368c2379c200a2df5f448c633928cc36fab37d6cc0359dab52d7289dcb81a109457c8976c733578d1374030c83d36d4cd47cfbb33

test:
  secret_key_base: 721278c50eff93235dc4d43482fc2f7566fc20a5076df7e67ea460e52b160425387e9b0381e5360239ae2a34fc98a6b786f73e6a5803da7b5aff9fd3bcef5260

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
